-- CLIENTES
create table if not exists clientes (
  cpf varchar(20) primary key,
  nome varchar(120) not null,
  celular varchar(40),
  endereco varchar(200),
  email varchar(120) not null
);

-- INGREDIENTES
create table if not exists ingredientes (
  id bigint primary key,
  descricao varchar(255) not null
);

-- PRODUTOS
create table if not exists produtos (
  id bigint primary key,
  descricao varchar(120) not null,
  preco int not null,
  disponivel boolean not null default true
);

-- RECEITAS
create table if not exists receitas (
  id bigint generated by default as identity primary key,
  titulo varchar(120) not null
);

-- RECEITA x INGREDIENTE
create table if not exists receita_ingrediente (
  receita_id bigint not null,
  ingrediente_id bigint not null,
  quantidade int not null,
  primary key (receita_id, ingrediente_id),
  foreign key (receita_id) references receitas(id),
  foreign key (ingrediente_id) references ingredientes(id)
);

-- CARDÁPIOS
create table if not exists cardapios (
  id bigint generated by default as identity primary key,
  titulo varchar(120) not null, 
  ativo boolean not null
);

-- CARDÁPIO x PRODUTO
create table if not exists cardapio_produto (
  cardapio_id bigint not null,
  produto_id bigint not null,
  primary key (cardapio_id, produto_id),
  foreign key (cardapio_id) references cardapios(id),
  foreign key (produto_id) references produtos(id)
);

-- PRODUTO x RECEITA
create table if not exists produto_receita (
  produto_id bigint primary key,
  receita_id bigint not null,
  foreign key (produto_id) references produtos(id),
  foreign key (receita_id) references receitas(id)
);

-- PEDIDOS
create table if not exists pedidos (
  id bigint generated by default as identity primary key,
  cliente_cpf varchar(20) not null,
  status varchar(30) not null,
  data_hora_pagamento timestamp,
  valor double not null,
  impostos double not null,
  desconto double not null,
  valor_cobrado double not null,
  data_pedido date default current_date,
  foreign key (cliente_cpf) references clientes(cpf)
);

-- ITENS DO PEDIDO
create table if not exists itens_pedido (
  pedido_id bigint not null,
  produto_id bigint not null,
  quantidade int not null,
  foreign key (pedido_id) references pedidos(id),
  foreign key (produto_id) references produtos(id)
);
