create table if not exists clientes(
  cpf varchar(15) not null primary key,
  nome varchar(100) not null,
  celular varchar(20) not null,
  endereco varchar(255) not null,
  email varchar(255) not null
);

create table if not exists ingredientes (
  id bigint primary key,
  descricao varchar(255) not null
);

create table if not exists itensEstoque(
    id bigint primary key,
    quantidade int,
    ingrediente_id bigint,
    foreign key (ingrediente_id) references ingredientes(id)
);

-- RECEITAS
create table if not exists receitas (
  id bigint generated by default as identity primary key,
  titulo varchar(120) not null
);

-- Tabela de relacionamento entre Receita e Ingrediente
create table if not exists receita_ingrediente (
  receita_id bigint not null,
  ingrediente_id bigint not null,
  quantidade int not null,
  primary key (receita_id, ingrediente_id),
  foreign key (receita_id) references receitas(id),
  foreign key (ingrediente_id) references ingredientes(id)
);

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
-- CARDÁPIO
create table if not exists cardapios (
  id bigint generated by default as identity primary key,
  titulo varchar(120) not null, 
  ativo boolean not null
=======
-- Tabela de Produtos
create table if not exists produtos (
  id bigint primary key,
  descricao varchar(255) not null,
  preco bigint
>>>>>>> e9847fe (implementacao final (ou quase))
);

-- Tabela de relacionamento entre Produto e Receita
create table if not exists produto_receita (
  produto_id bigint not null,
  receita_id bigint not null,
  primary key (produto_id,receita_id),
  foreign key (produto_id) references produtos(id),
  foreign key (receita_id) references receitas(id)
);

-- Tabela de Cardapios
create table if not exists cardapios (
  id bigint primary key,
  titulo varchar(255) not null
);

-- Tabela de relacionamento entre Cardapio e Produto
=======
-- MAPEAMENTO PRODUTO → RECEITA
create table if not exists produto_receita (
  produto_id bigint not null,
  receita_id bigint not null,
  primary key (produto_id, receita_id),
  foreign key (produto_id) references produtos(id),
  foreign key (receita_id) references receitas(id)
);

=======
>>>>>>> 91f6cf2 (mais alguns ajustes, todos modulos e curl rodando)
-- CARDÁPIOS
create table if not exists cardapios (
  id bigint generated by default as identity primary key,
  titulo varchar(120) not null, 
  ativo boolean not null
);

<<<<<<< HEAD
>>>>>>> d83a0c4 (ajustando erros dos modulos nao subirem)
=======
-- CARDÁPIO x PRODUTO
>>>>>>> 91f6cf2 (mais alguns ajustes, todos modulos e curl rodando)
create table if not exists cardapio_produto (
  cardapio_id bigint not null,
  produto_id bigint not null,
  primary key (cardapio_id,produto_id),
  foreign key (cardapio_id) references cardapios(id),
  foreign key (produto_id) references produtos(id)
);

<<<<<<< HEAD
-- Tabela de Pedidos
=======
-- PRODUTO x RECEITA
create table if not exists produto_receita (
  produto_id bigint primary key,
  receita_id bigint not null,
  foreign key (produto_id) references produtos(id),
  foreign key (receita_id) references receitas(id)
);

-- PEDIDOS
>>>>>>> 91f6cf2 (mais alguns ajustes, todos modulos e curl rodando)
create table if not exists pedidos (
<<<<<<< HEAD
  id bigint auto_increment primary key,
  cliente_cpf varchar(15) not null,
  status varchar(20) not null,
=======
  id bigint generated by default as identity primary key,
  cliente_cpf varchar(20) not null,
  status varchar(30) not null,
>>>>>>> d83a0c4 (ajustando erros dos modulos nao subirem)
  data_hora_pagamento timestamp,
  valor double not null,
  impostos double not null,
  desconto double not null,
  valor_cobrado double not null,
  data_pedido date default current_date,
  foreign key (cliente_cpf) references clientes(cpf)
);

-- Itens do pedido
create table if not exists itens_pedido (
  pedido_id bigint not null,
  produto_id bigint not null,
  quantidade int not null,
  foreign key (pedido_id) references pedidos(id),
  foreign key (produto_id) references produtos(id)
);
